{
  "name": "Publish Gradle Maven Publications to GitHub Attest Build Provenance",
  "description": "This action extracts all Gradle maven publications and publish them to GitHub",

  "inputs": {
    "version": {
      "description": "The release version of the Gradle project",
      "required": true
    },
    "setup-version": {
      "description": "The version of this action. This workaround is needed until Immutable Actions are available.",
      "required": true
    },
  },

  "runs": {
    "using": "composite",
    "steps": [
      {
        "uses": "hfhbd/extract-publications/setup-action@v${{ inputs.setup-version }}",
        "with": {
          "version": "${{ inputs.setup-version }}"
        }
      },
      {
        "name": "Write outputs",
        "id": "publications",
        "run": "./gradlew writePublicationsToGitHubOutputFile -Pversion=${{ inputs.version }}",
        "shell": "bash",
      },
      {
        "uses": "actions/attest-build-provenance@v2",
        "with": {
          "subject-path": "${{ steps.publications.outputs.publishedFiles }}",
        }
      }
    ]
  }
}
